### ISSUE TITLE
NameError: name 'hic' is not defined

### ISSUE THREAD

**Issue by liudonghua123** [stefanofranzini/essHIC#1]
After I installed `essHIC`, I tried to execute `tutorial.py`, but I got the following errors. It seems some lib code is missing like `hic`, `pseudo` function.

https://github.com/stefanofranzini/essHIC/blob/7baf917e67d738214487d166a93ae98a8c5a743d/essHIC/essHIC/ess.py#L179-L189

```shell
(essHIC) D:\code\python\essHIC\essHIC\tutorial>python tutorial.py

         ##############################################################################################################################
         ##########
           #
         ######:::##
           #
         ####::::::##                                                 HHHHHHHHH     HHHHHHHHHIIIIIIIIII      CCCCCCCCCCCCC 
           #
         ##:::::::::##                                                H:::::::H     H:::::::HI::::::::I   CCC::::::::::::C 
           #
         ##############                                               H:::::::H     H:::::::HI::::::::I CC:::::::::::::::C 
           #
         #                                                            HH::::::H     H::::::HHII::::::IIC:::::CCCCCCCC::::C 
           #
         #          eeeeeeeeeeee        ssssssssss       ssssssssss     H:::::H     H:::::H    I::::I C:::::C       CCCCCC 
           #
         #        ee::::::::::::ee    ss::::::::::s    ss::::::::::s    H:::::H     H:::::H    I::::IC:::::C
           #
         #       e::::::eeeee:::::eess:::::::::::::s ss:::::::::::::s   H::::::HHHHH::::::H    I::::IC:::::C
           #
         #      e::::::e     e:::::es::::::ssss:::::ss::::::ssss:::::s  H:::::::::::::::::H    I::::IC:::::C
           #
         #      e:::::::eeeee::::::e s:::::s  ssssss  s:::::s  ssssss   H:::::::::::::::::H    I::::IC:::::C
           #
         #      e:::::::::::::::::e    s::::::s         s::::::s        H::::::HHHHH::::::H    I::::IC:::::C
           #
         #      e::::::eeeeeeeeeee        s::::::s         s::::::s     H:::::H     H:::::H    I::::IC:::::C
           #
         #      e:::::::e           ssssss   s:::::s ssssss   s:::::s   H:::::H     H:::::H    I::::I C:::::C       CCCCCC 
           #
         #      e::::::::e          s:::::ssss::::::ss:::::ssss::::::sHH::::::H     H::::::HHII::::::IIC:::::CCCCCCCC::::C 
           #
         #       e::::::::eeeeeeee  s::::::::::::::s s::::::::::::::s H:::::::H     H:::::::HI::::::::I CC:::::::::::::::C 
           #
         #        ee:::::::::::::e   s:::::::::::ss   s:::::::::::ss  H:::::::H     H:::::::HI::::::::I   CCC::::::::::::C 
           #
         #          eeeeeeeeeeeeee    sssssssssss      sssssssssss    HHHHHHHHH     HHHHHHHHHIIIIIIIIII      CCCCCCCCCCCCC 
           #
         #
           #
         #
           #
         ##############################################################################################################################
hic001 HIC001 nrm chr17 100kb
hic002 HIC002 nrm chr17 100kb
hic003 HIC003 nrm chr17 100kb
hic004 HIC004 nrm chr17 100kb
hic005 HIC005 nrm chr17 100kb
hic006 HIC006 nrm chr17 100kb
hic007 HIC050 nrm chr17 100kb
hic008 HIC051 nrm chr17 100kb
hic009 HIC053 nrm chr17 100kb
hic010 Jin_IMR90_HindIII_A nrm chr17 100kb
hic011 Jin_IMR90_HindIII_C nrm chr17 100kb
hic012 Jin_IMR90_HindIII_D nrm chr17 100kb
hic001 HIC001 nrm chr17 100kb
hic002 HIC002 nrm chr17 100kb
hic003 HIC003 nrm chr17 100kb
hic004 HIC004 nrm chr17 100kb
hic005 HIC005 nrm chr17 100kb
hic006 HIC006 nrm chr17 100kb
hic007 HIC050 nrm chr17 100kb
hic008 HIC051 nrm chr17 100kb
hic009 HIC053 nrm chr17 100kb
hic010 Jin_IMR90_HindIII_A nrm chr17 100kb
hic011 Jin_IMR90_HindIII_C nrm chr17 100kb
hic012 Jin_IMR90_HindIII_D nrm chr17 100kb
hicA contains experiment HIC001, chromosome 17, its cell-type is GM12878
hicB contains experiment Jin_IMR90_HindIII_D, chromosome 17, its cell-type is IMR90
C:\Users\Liu.D.H\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\essHIC\hic.py:386: MatplotlibDeprecationWarning: Passing the minor parameter of set_ticks() positionally is deprecated since Matplotlib 3.2; the parameter will become keyword-only two minor releases later.
  ax.set_xticks([],[])
C:\Users\Liu.D.H\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\essHIC\hic.py:387: MatplotlibDeprecationWarning: Passing the minor parameter of set_ticks() positionally is deprecated since Matplotlib 3.2; the parameter will become keyword-only two minor releases later.
  ax.set_yticks([],[])
Traceback (most recent call last):
  File "tutorial.py", line 63, in <module>
    mydistance.get_spectra(100)                         # compute and store eigenspaces of all matrices in the dataset, up to the 100th  
  File "C:\Users\Liu.D.H\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\essHIC\ess.py", line 73, in get_spectra
    tmp_hic = hic(f)
NameError: name 'hic' is not defined

(essHIC) D:\code\python\essHIC\essHIC\tutorial>
```

**Comment by stefanofranzini** [comment]
Hi, I am having trouble reproducing your issue (that is: I am able to run the tutorial without any trouble). 

Could you please tell me which version of essHIC you have installed? Did you install it using pip or from the repository? Did you install the python3 or python2.7 version?

**Comment by stefanofranzini** [comment]
Hi, I finally managed to reproduce the issue on local and fix the bugs. Strangely enough the issue does not seem to arise when installing the package via pip3. Nevertheless you can now clone and use the fixed package.

**Comment by liudonghua123** [comment]
Thanks, it seems fixed. 😄
